name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-test-musl-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Run tests
      run: cargo test --verbose
      
    - name: Test musl build
      run: cargo build --target x86_64-unknown-linux-musl --verbose

  build:
    name: Build and Package
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install cargo-deb
      run: cargo install cargo-deb
      
    - name: Build release binary with musl (static linking)
      run: |
        # Build with musl for universal compatibility (no GLIBC dependencies)
        cargo build --release --target x86_64-unknown-linux-musl --verbose
      
    - name: Create .deb package
      run: cargo deb --target x86_64-unknown-linux-musl --no-build --verbose
      
    - name: Verify binary compatibility
      run: |
        echo "Checking binary compatibility..."
        BINARY="target/x86_64-unknown-linux-musl/release/f2b-buxjr"
        if [ -f "$BINARY" ]; then
          echo "Binary exists: $BINARY"
          file "$BINARY"
          ldd "$BINARY" || echo "Statically linked binary (expected)"
        else
          echo "❌ Binary not found: $BINARY"
          exit 1
        fi
      
    - name: List generated files
      run: |
        echo "Generated .deb package:"
        find target/x86_64-unknown-linux-musl/debian -name "*.deb" -ls
        echo "Package contents:"
        dpkg-deb --contents target/x86_64-unknown-linux-musl/debian/*.deb
        
    - name: Upload .deb as artifact (for main branch)
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: f2b-buxjr-deb-package
        path: target/x86_64-unknown-linux-musl/debian/*.deb
        retention-days: 30
        
    - name: Upload .deb to release (for releases)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/x86_64-unknown-linux-musl/debian/f2b-buxjr_${{ github.event.release.tag_name }}_amd64.deb
        asset_name: f2b-buxjr_${{ github.event.release.tag_name }}_amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload .deb to latest release (for version changes)
      if: github.ref == 'refs/heads/main'
      run: |
        # Get the current version from Cargo.toml
        VERSION=$(grep '^version = ' Cargo.toml | cut -d'"' -f2)
        echo "Current version: $VERSION"
        
        # Check if a release exists for this version
        if gh release view "v$VERSION" >/dev/null 2>&1; then
          echo "Release v$VERSION exists, uploading .deb file..."
          
          # Find the generated .deb file
          DEB_FILE=$(find target/x86_64-unknown-linux-musl/debian -name "*.deb" -type f | head -1)
          if [ -n "$DEB_FILE" ]; then
            echo "Uploading $DEB_FILE to release v$VERSION"
            gh release upload "v$VERSION" "$DEB_FILE" --clobber
            echo "✅ Successfully uploaded .deb to release v$VERSION"
          else
            echo "❌ No .deb file found in target/x86_64-unknown-linux-musl/debian"
            exit 1
          fi
        else
          echo "No release found for v$VERSION, skipping upload"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}